services:
  backend:
    build: src
    container_name: backend_basis
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    networks:
      - basis-network
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db_basis
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - basis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  basis-network:
    driver: bridge

volumes:
  pg_data: